public class SUTC {
    public static final Decimal AGE_FLOOR_MAMMOGRAM = 50;
    public static final Decimal AGE_CEILING_MAMMOGRAM = 74;
    public static final Decimal AGE_FLOOR_PAP_TEST = 21;
    public static final Decimal AGE_CEILING_PAP_TEST = 65;
    public static final Decimal AGE_FLOOR_COLONOSCOPY = 50;
    public static final Decimal AGE_CEILING_COLONOSCOPY = 75;
    public static final Decimal AGE_CEILING_HPV = 26;

    public static final Decimal AGE_ADULT = 18;
    public static final Decimal AGE_MAX = 150;

    public static final String SEX_MALE = 'male';
    public static final String SEX_FEMALE = 'female';

    public static final String BASE_URL = 'https://www.getscreenednow.org';
    public static final String SURVEY_URL = 'https://www.getscreenednow.org/survey/';
    public static final String ASSETS_URL = 'https://d37m4c6899pm9g.cloudfront.net/assets/';
    public static final String RALLY_URL = 'https://www.rallyhealth.com';
   
    public static final String EMAIL_FROM = 'Rally <no-reply@rallyhealth.com>';
    public static final String EMAIL_SUBJECT = 'Here is your checklist from Rally!';    
    public static final String MAILGUN_API_KEY = 'key-4c57dc4198e3ab7320cafb6d60c5b84a';
    public static final String MAILGUN_API_ENDPOINT = 'https://api.mailgun.net/v3/mg.rallyhealth.com/messages';

}